# Generated by Django 3.2.13 on 2022-05-01 21:08

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscribed__exact', django.db.models.expressions.F('subscriber')), _negated=True), name='subscription_subscribed_not_equals_subscriber'),
        ),
    ]
