# Generated by Django 3.2.13 on 2022-05-21 07:46

import colorfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20220519_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='in_baskets',
            field=models.ManyToManyField(related_name='basket_recipes', to=settings.AUTH_USER_MODEL, verbose_name='В корзинах у'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_favorites',
            field=models.ManyToManyField(related_name='favor_recipes', to=settings.AUTH_USER_MODEL, verbose_name='В избранных у'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FFFF00', 'yellow'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#00FF00', 'green')], unique=True, verbose_name='Цвет'),
        ),
    ]
